/* Generated Template */

ListIt.templates['help'] = function(obj){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'')};
with(obj||{}){
__p+='<div id="help-firefox" class="help-platform">\n    <h3>Firefox</h3>\n    <h4>Toolbar Icon</h4>\n    <p>\n        You\'ll notice that the List.it icon was automatically added to your Add-on Bar.\n        Clicking this will toggle the sidebar.\n    </p>\n    <p>\n        Firefox gives you a lot of freedom to customize the way your toolbars look. If\n        you want the List.it icon to be somewhere else, just right click on one of your\n        toolbars and select \'Customize.\' This will allow you to click and drag the icon,\n        and even remove it completely.\n    </p>\n    <h4>View Menu Item</h4>\n    <p>\n        You can also toggle the sidebar from the Firefox menu. At the top of your browser,\n        you can go to View>Sidebar>List.it which will allow you to open and close the sidebar.\n    </p>\n    <p>\n        If you don\'t see a View button, you have your Menu Bar hidden. You can make it appear\n        by right clicking on one of your toolbars and clicking on \'Menu Bar.\'\n    </p>\n    <h4>Hotkey</h4>\n    <p>\n        For your convenience, we\'ve given you a hotkey that you can use anywhere in Firefox.\n        It works about the same way the toolbar button does, but it can also focus the sidebar.\n        This means that if you\'re browsing the web while the sidebar is open, you can hit the\n        hotkey and your cursor will go straight to the note creator.\n        It has a default keyboard shortcut but you can change it by going to the Options Page\n        and adjusting your settings.\n    </p>\n    <table>\n        <tr>\n            <th>Default Shortcut</th><th>Use</th>\n        </tr>\n        <tr>\n            <td>Control+Shift+L</td><td><b>Open/Close the sidebar</b></td>\n        </tr>\n    </table>\n</div>\n';
}
return __p;
};
